@echo off
rem Copy to bench_config.local.bat and edit for the bench.
set "ERESISTOR_HOST=192.168.0.55"
set "ERESISTOR_GATE=G5"
set "ERESISTOR_OUTPUT_DIR=%REGRESSION_ROOT%\results\robot"
set "ERESISTOR_SERIAL_PORT=COM17"
set "ERESISTOR_DMM_RESOURCE=auto"
set "ERESISTOR_DMM_IDN_CONTAINS=34401"
set "ERESISTOR_HIL_CHANNEL=1"
set "ERESISTOR_HIL_REPEAT_CYCLES=50"
set "ERESISTOR_ALLOW_ACTIVE_OUTPUT_TESTS=false"
set "ERESISTOR_FIXTURE_CONFIRMATION="
