@echo off
rem Shared initialization for E-Resistor Windows launchers.
rem This file is intended to be called from another batch file.

set "REGRESSION_ROOT=%~dp0..\.."
for %%I in ("%REGRESSION_ROOT%") do set "REGRESSION_ROOT=%%~fI"
set "ROBOT_ROOT=%REGRESSION_ROOT%\robot_framework"
set "LOCAL_BENCH_CONFIG=%ROBOT_ROOT%\variables\bench_config.local.bat"

rem Safe defaults. bench_config.local.bat may override them.
if not defined ERESISTOR_HOST set "ERESISTOR_HOST=192.168.0.55"
if not defined ERESISTOR_HTTP_PORT set "ERESISTOR_HTTP_PORT=80"
if not defined ERESISTOR_SCPI_PORT set "ERESISTOR_SCPI_PORT=5025"
if not defined ERESISTOR_TIMEOUT set "ERESISTOR_TIMEOUT=3.0"
if not defined ERESISTOR_GATE set "ERESISTOR_GATE=G3"
if not defined ERESISTOR_OUTPUT_DIR set "ERESISTOR_OUTPUT_DIR=%REGRESSION_ROOT%\results\robot"
if not defined ERESISTOR_ITERATIONS set "ERESISTOR_ITERATIONS=30"
if not defined ERESISTOR_STRESS_ITERATIONS set "ERESISTOR_STRESS_ITERATIONS=100"
if not defined ERESISTOR_HEAP_DRIFT_LIMIT set "ERESISTOR_HEAP_DRIFT_LIMIT=2048"
if not defined ERESISTOR_LATENCY_REGRESSION_PERCENT set "ERESISTOR_LATENCY_REGRESSION_PERCENT=15.0"
if not defined ERESISTOR_SERIAL_PORT set "ERESISTOR_SERIAL_PORT=auto"
if not defined ERESISTOR_SERIAL_BAUD set "ERESISTOR_SERIAL_BAUD=115200"
if not defined ERESISTOR_SERIAL_MATCH set "ERESISTOR_SERIAL_MATCH="
if not defined ERESISTOR_DMM_RESOURCE set "ERESISTOR_DMM_RESOURCE=auto"
if not defined ERESISTOR_DMM_IDN_CONTAINS set "ERESISTOR_DMM_IDN_CONTAINS=34401"
if not defined ERESISTOR_DMM_BACKEND set "ERESISTOR_DMM_BACKEND="
if not defined ERESISTOR_DMM_INIT_COMMANDS set "ERESISTOR_DMM_INIT_COMMANDS=*CLS|CONF:RES AUTO|TRIG:SOUR IMM|SAMP:COUN 1"
if not defined ERESISTOR_DMM_MEASURE_COMMAND set "ERESISTOR_DMM_MEASURE_COMMAND=READ?"
if not defined ERESISTOR_HIL_CHANNEL set "ERESISTOR_HIL_CHANNEL=1"
if not defined ERESISTOR_HIL_BITS set "ERESISTOR_HIL_BITS=0-15"
if not defined ERESISTOR_HIL_COMBINATION_MASKS set "ERESISTOR_HIL_COMBINATION_MASKS=0003,0005,0009"
if not defined ERESISTOR_HIL_REPEAT_CYCLES set "ERESISTOR_HIL_REPEAT_CYCLES=50"
if not defined ERESISTOR_HIL_ERROR_LIMIT_PERCENT set "ERESISTOR_HIL_ERROR_LIMIT_PERCENT=1.0"
if not defined ERESISTOR_HIL_SETTLE_TIMEOUT set "ERESISTOR_HIL_SETTLE_TIMEOUT=20.0"
if not defined ERESISTOR_HIL_SAMPLE_COUNT set "ERESISTOR_HIL_SAMPLE_COUNT=5"
if not defined ERESISTOR_HIL_SAMPLE_INTERVAL set "ERESISTOR_HIL_SAMPLE_INTERVAL=0.25"
if not defined ERESISTOR_HIL_STABILITY_PERCENT set "ERESISTOR_HIL_STABILITY_PERCENT=0.20"
if not defined ERESISTOR_HIL_MINIMUM_WAIT set "ERESISTOR_HIL_MINIMUM_WAIT=0.5"
if not defined ERESISTOR_HIL_OFF_MIN_OHM set "ERESISTOR_HIL_OFF_MIN_OHM=50000000"
if not defined ERESISTOR_HIL_SERIAL_FAULT_PATTERNS set "ERESISTOR_HIL_SERIAL_FAULT_PATTERNS=fatal|panic|assert|hardfault|queue overflow"
if not defined ERESISTOR_ALLOW_ACTIVE_OUTPUT_TESTS set "ERESISTOR_ALLOW_ACTIVE_OUTPUT_TESTS=false"
if not defined ERESISTOR_FIXTURE_CONFIRMATION set "ERESISTOR_FIXTURE_CONFIRMATION="
if not defined ERESISTOR_BASELINE set "ERESISTOR_BASELINE="
if not defined ERESISTOR_GATE_MANIFEST set "ERESISTOR_GATE_MANIFEST=%REGRESSION_ROOT%\gate_acceptance.json"

if exist "%LOCAL_BENCH_CONFIG%" call "%LOCAL_BENCH_CONFIG%"

set "REGRESSION_PYTHON=%REGRESSION_ROOT%\.venv\Scripts\python.exe"
set "ROBOT_PYTHON=%REGRESSION_PYTHON%"
if not exist "%REGRESSION_PYTHON%" (
    echo ERROR: Python virtual environment not found:
    echo   %REGRESSION_PYTHON%
    echo Run setup_robot_environment.bat first.
    exit /b 2
)

if not exist "%ROBOT_ROOT%\run_robot.py" (
    echo ERROR: Robot launcher not found in %ROBOT_ROOT%.
    exit /b 2
)

exit /b 0
