/** @file calibration_api.h @brief Calibration, resistance, safety, profile and storage interfaces. */
#pragma once
#include "runtime_state.h"
void copyDefaultConfigToRuntime();
const char* mosfetNameForBit(uint8_t bit);
float getRuntimeResistanceOhms(uint8_t channelIndex, uint8_t bit);
String channelConfigPath(uint8_t channelIndex);
String networkConfigPath();
String channelConfigToText(uint8_t channelIndex);
bool getChannelConfigStorageInfo(uint8_t channelIndex, bool& exists, size_t& sizeBytes);
String calibrationFileListText();
String allChannelConfigsToBundleText();
bool restoreAllChannelConfigsFromBundleText(const String& text, char* error, size_t errorLen);
bool parseCsvConfigLine(const String& line, ParsedResistorInfo& out);
bool parseHeaderInitializerLine(const String& line, ParsedResistorInfo& out);
bool parseChannelConfigText(uint8_t channelIndex, const String& text, char* error, size_t errorLen);
bool saveChannelConfigToLittleFS(uint8_t channelIndex);
bool loadChannelConfigFromLittleFS(uint8_t channelIndex);
void loadAllRuntimeConfigs();
bool allChannelsHaveSavedCalibration();
String calibrationStorageStatusText();
void rebuildConductanceCache();
void invalidateConductanceCache();
bool parseResistanceOhms(const char* text, double& ohms);
String formatResistanceOhms(double ohms);
String calculateOutputResistanceText(uint8_t channelIndex, uint16_t mask);
bool formatOutputResistanceText(uint8_t channelIndex, uint16_t mask, char* destination, size_t destinationLength);
bool calculateEquivalentOhms(uint8_t channelIndex, uint16_t mask, double& outOhms);
uint8_t countActiveBits16(uint16_t mask);
bool checkMaskSafety(uint8_t channelIndex, uint16_t mask, char* reason, size_t reasonLen);
String resistanceCssClass(uint8_t channelIndex, uint16_t mask);
String safetyConfigPath();
String calibrationMetaPath(uint8_t channelIndex);
void appendLogEvent(const char* text);
String sanitizeName(String name);
String profilePathFromName(String name);
bool saveSafetyConfigToLittleFS();
bool loadSafetyConfigFromLittleFS();
bool calculateNearestMaskForTarget(uint8_t channelIndex, double targetOhm, TargetSearchResult& result, uint32_t deadlineUs = 2000000UL);
bool findNearestMaskForTarget(uint8_t channelIndex, double targetOhm, uint16_t& bestMask, double& bestOhm, double& bestErrorPercent);
void requestTargetSearchCancel();
void clearTargetSearchCancel();
String profileListOptions();
bool loadProfileMasks(String profileName, uint16_t masks[CHANNEL_COUNT]);
bool saveCurrentProfile(String profileName);
void appendProfileManager(String& html);
void appendSafetySummaryCard(String& html);
void appendCombinedChannelResistorTable(String& html);
void appendLiveStateScript(String& html);
void appendBitIndicator(String& html, uint8_t channelIndex, uint16_t mask);
String u64ToString(uint64_t value);
String formatBytesHuman(uint64_t bytes);
void appendLittleFsCombinedFiles(String& html);
void appendLittleFsStorageInfo(String& html);
